"""
Django settings for RAGchatbot project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import datetime


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Khởi tạo
env = environ.Env()
# Chỉ định rõ đường dẫn file .env
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# JWT
ACCESS_TOKEN_LIFETIME = datetime.timedelta(minutes=env.int("ACCESS_TOKEN_LIFETIME", default=15))
SECURE_COOKIE = env.bool("SECURE_COOKIE", default=False)
SECRET_KEY_JWT = env("SECRET_KEY_JWT")

# File size 
MAX_MB = env.int("MAX_MB", default=20)

# Embedding model
EMBEDDING_MODEL = env("EMBEDDING_MODEL")

# Qdrant
QDRANT_URL = env("QDRANT_URL")
QDRANT_API_KEY = env("QDRANT_API_KEY")
COLLECTION_NAME = env("COLLECTION_NAME")

# Redis / Valkey
VALKEY_URL = env("VALKEY_URL")

# Groq API
OPENAI_API_KEY = env("OPENAI_API_KEY")
OPENAI_API_BASE = env("OPENAI_API_BASE")
GROQ_API_KEY = env("GROQ_API_KEY")

# Database
DB_SSL_CA = os.path.join(BASE_DIR, "certs", "ca.pem")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v()x6jbow+&gt6%ly=9k+uemx%#vj%-lr9l5!632c(^9qc^p&#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RAGchatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    BASE_DIR / 'static' ,
]

WSGI_APPLICATION = 'RAGchatbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'db_Annie': {   # PostgreSQL
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': 'AVNS_S9lnapsijm-PMfm40-H',
        'HOST': 'rag-log-tracking-rag-log-tracking.c.aivencloud.com',
        'PORT': '18856',
    },
    'db_Huy': {   # MySQL
        'ENGINE': 'django.db.backends.mysql',
        'HOST': env("DB_HOST"),
        'PORT': env.int("DB_PORT"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'NAME': env("DB_NAME"),
        'OPTIONS': {
            "ssl": {"ca": DB_SSL_CA}
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

DOCS_ROOT = BASE_DIR / 'docs'
EXTRACTED_IMAGES_ROOT = BASE_DIR / 'extracted_images'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
