# Generated by Django 5.2.5 on 2025-08-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ngày / Phiên test')),
                ('user_question', models.TextField(verbose_name='Câu hỏi của người dùng')),
                ('rag_answer', models.TextField(verbose_name='Câu trả lời RAG')),
                ('accuracy', models.CharField(max_length=20, verbose_name='Accuracy (đúng/sai hoặc % điểm)')),
                ('latency', models.FloatField(verbose_name='Latency (s)')),
                ('user_satisfaction', models.IntegerField(verbose_name='User Satisfaction (1–5)')),
            ],
        ),
    ]
