# Generated by Django 5.2.5 on 2026-04-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_role_name_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(db_table='user_roles', to='chat.role'),
        ),
        migrations.AlterModelTable(
            name='logentry',
            table='log_entries',
        ),
        migrations.AlterModelTable(
            name='prompt',
            table='prompts',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
