# Generated by Django 5.2.5 on 2026-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('summary', 'Summary'), ('generate', 'Generate Response'), ('query_rewriter', 'Query Rewriter')], max_length=50),
        ),
    ]
